---
upload-to-database:
  import:
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: supermarket_sales

cleaned-upload-to-database:
  import:
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: table1
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: table2
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: table3

sql_python:
  export:
    - export:
        host: s3
        bucket: end2enddsproject
        filename: supermarket_cleaned

modeling_final:
  export:
    - export:
      host: gsheet
      spread_sheet_id: 1d9qOwKAaOVdkyuubjCycIcPO_H7ASbUkk_tN75JF2go
      worksheet_name: Sheet1